language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda2-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda2/bin/activate root
      conda install --yes --quiet qt=4 pyqt=4
      conda install --yes --quiet -c conda-forge boost boost-cpp fftw
      conda install --yes --quiet -c jmbell ftgl
      conda install --yes --quiet bsddb freetype gsl hdf5 ipython jpeg libpng libtiff matplotlib numpy=1.11 pyopengl=3.0 scikit-learn scipy theano tk cmake openmpi

      export CONDA_BUILD_STATE=BUILD
      export PREFIX=$HOME/miniconda2/
      export SP_DIR=$PREFIX/lib/python2.7/site-packages
      
      export build_dir=build_eman

script:
  - rm -rf ${build_dir}
  - mkdir -p ${build_dir}
  - cd ${build_dir}

  - cmake ..
  - make
  - make install
  - source ../ci_support/run_circle_post.sh
