language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27 MINICONDA_FILE="Miniconda2-latest-MacOSX-x86_64.sh"


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    - source ci_support/pre_build.sh

      export CONDA_BUILD_STATE=BUILD
      export PREFIX=$HOME/miniconda2/
      export SP_DIR=$PREFIX/lib/python2.7/site-packages
      
      export build_dir=build_eman

script:
  - rm -rf ${build_dir}
  - mkdir -p ${build_dir}
  - cd ${build_dir}

  - cmake ..
  - make
  - make install
  
  - export PYTHONPATH="${PREFIX}/lib:$PYTHONPATH"

  - source ../ci_support/post_build.sh
