environment:

  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64


# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    - cmd: set
    # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    - cmd: rmdir C:\cygwin /s /q

    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    - cmd: set PYTHONUNBUFFERED=1

    # Add our channels.
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --add channels conda-forge

    # Configure the VM.
    - cmd: set CPU_COUNT=2
    - cmd: conda install --quiet --yes obvious-ci
    - cmd: conda config --set add_pip_as_python_dependency false
    - cmd: conda install -n root --yes --quiet vs2008_express_vc_python_patch
    - cmd: call setup_x64
    - cmd: conda info
    - cmd: conda config --get


# Skip .NET project specific build phase.
build: off
