environment:

  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64


platform:
    - x64

install:
    - cmd: set
    # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    - cmd: rmdir C:\cygwin /s /q

    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: set PYTHONUNBUFFERED=1
    - cmd: set CPU_COUNT=2

    - cmd: conda config --set show_channel_urls true

    - cmd: conda install -n root --yes --quiet vs2008_express_vc_python_patch -c conda-forge
    - cmd: call setup_x64

    - cmd: conda install --quiet --yes conda-build
    - cmd: conda update --yes --quiet conda -c defaults

    - cmd: conda info
    - cmd: conda config --get


# Skip .NET project specific build phase.
build: off

test_script:
    - conda build %APPVEYOR_BUILD_FOLDER%\recipes\eman -c cryoem -c defaults -c conda-forge
