package:
    name: eman2
    version: 2.2

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "python 2.7.*",
            "boost 1.61.*",
            "fftw",
            "numpy",
            "ftgl",
            "freetype",
            "gsl",
            "hdf5",
            "jpeg",
            "libtiff",
            "libpng",
            "zlib",
    ] %}
    
    build:
        - cmake
        - szip  # [win]
        
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
        
        - szip  # [win]
        - bsddb  # [not win]
        - matplotlib
        - ipython
        - pyqt 4.*
        - pyopengl 3.1.0
        - theano
        - pydusa  # [not win]

test:
  imports:   # [not win]
    - mpi    # [not win]
  
  commands:
    - e2version.py
    - e2speedtest.py
    - e2display.py -h
    - test -f ${PREFIX}/examples/mpi_test.py                        # [not win]
    - mpirun -n 4 $(which python) ${PREFIX}/examples/mpi_test.py    # [not win]
    - if not exist %LIBRARY_PREFIX%\\examples\\mpi_test.py  exit 1  # [win]
    - e2RCTboxer.py -h
    - e2a2d_align.py -h
    - e2a2d_average.py -h
    - e2a2d_stat.py -h
    - e2align2d.py -h
    - e2align3d.py -h
    - e2basis.py -h
    - e2bdb.py -h
    - e2boxadjust.py -h
    - e2boxer.py -h
    - e2boxer_old.py -h
    - e2buildsets.py -h
    - e2buildstacks.py -h
    - e2classaverage.py -h
    - e2classes_denovo.py -h
    - e2classextract.py -h
    - e2classify.py -h
    - e2classifykmeans.py -h
    - e2classifyligand.py -h
    - e2classifytree.py -h
    - e2classptcl.py -h
    - e2classvsproj.py -h
    - e2cmmtomrc.py -h
    - e2ctf.py -h
    - e2ctf2eman1.py -h
    - e2ctf_auto.py -h
    - e2ctffind3util.py -h
    - e2ctfsim.py -h
    - e2ddd_movie.py -h
    - e2ddd_particles.py -h
    - e2display.py -h
    - e2emx.py -h
    - e2eotest.py -h
    - e2erasefiducials.py -h
    - e2euler_refine.py -h
    - e2eulerxplor.py -h
    - e2evalimage.py -h
    - e2evalparticles.py -h
    - e2evalrefine.py -h
    - e2extractsubparticles.py -h
    - e2filtertool.py -h
    - e2foldfitter.py -h
    - e2fsc.py -h
    - e2helixboxer.py -h
    - e2help.py -h
    - e2history.py -h
    - e2iminfo.py -h
    - e2import.py -h
    - e2initialmodel.py -h
    - e2initialmodel_hisym.py -h
    - e2make3d.py -h
    - e2make3dpar.py -h
    - e2match.py -h
    - e2motion.py -h
    - e2msa.py -h
    - e2parallel.py -h
    - e2pathwalker.py -h
    - e2pdb2mrc.py -h
    - e2plotEulers.py -h
    - e2proc2d.py -h
    - e2proc2dmulti.py -h
    - e2proc3d.py -h
    - e2proclst.py -h
    - e2procpdb.py -h
    - e2proctxt.py -h
    - e2procxml.py -h
    - e2project3d.py -h
    - e2projectupdate21.py -h
    - e2ptcltrace.py -h
    - e2ptclvsmap.py -h
    - e2rawdata.py -h
    - e2rct.py -h
    - e2refine.py -h
    - e2refine2d.py -h
    - e2refine_easy.py -h
    - e2refine_postprocess.py -h
    - e2refine_split.py -h
    - e2refinefromfrealign.py -h
    - e2refinemulti.py -h
    - e2refinemultinoali.py -h
    - e2refinetofrealign.py -h
    - e2refinetorelion3d.py -h
    - e2refinevariance.py -h
    - e2reliontoeman.py -h
    - e2runfrealign.py -h
    - e2runresmap.py -h
    - e2scannereval.py -h
    - e2segment3d.py -h
    - e2seq2pdb.py -h
    - e2simmx.py -h
    - e2simmx2stage.py -h
    - e2simmxxplor.py -h
    - e2skelpath.py -h
    - e2sparxtoeman.py -h
    - e2speedtest.py -h
    - e2spt_align.py -h
    - e2spt_autoboxer.py -h
    - e2spt_average.py -h
    - e2spt_average_multi.py -h
    - e2spt_binarytree.py -h
    - e2spt_boxer.py -h
    - e2spt_classaverage.py -h
    - e2spt_ctf.py -h
    - e2spt_fftamp.py -h
    - e2spt_hac.py -h
    - e2spt_intrafsc.py -h
    - e2spt_isr.py -h
    - e2spt_preproc.py -h
    - e2spt_project.py -h
    - e2spt_recompute.py -h
    - e2spt_refinemsa.py -h
    - e2spt_refinemulti.py -h
    - e2spt_resolutionplot.py -h
    - e2spt_scramblestack.py -h
    - e2spt_simulation.py -h
    - e2spt_stat.py -h
    - e2spt_subtilt.py -h
    - e2spt_tiltstacker.py -h
    - e2spt_translate.py -h
    - e2spt_wedge.py -h
    - e2ssehunter.py -h
    - e2ssematch.py -h
    - e2stackanim.py -h
    - e2stacksort.py -h
    - e2symbest.py -h
    - e2symsearch3d.py -h
    - e2tilefile.py -h
    - e2tileimage.py -h
    - e2tiltvalidate.py -h
    - e2tomo_ctf.py -h
    - e2tomogram.py -h
    - e2tomopreproc.py -h
    - e2tomoresolution.py -h
    - e2tomoseg_buildtrainset.py -h
    - e2tomoseg_convnet.py -h
    - e2tvrecon.py -h
