package:
    name: eman2
    version: 2.2

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "python 2.7.*",
            "boost 1.61.*",
            "fftw",
            "numpy",
            "ftgl",
            "freetype",
            "gsl",
            "hdf5",
            "jpeg",
            "libtiff",
            "libpng",
            "zlib",
    ] %}
    
    build:
        - cmake
        - szip  # [win]
        
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
        
        - szip  # [win]
        - bsddb  # [not win]
        - matplotlib
        - ipython
        - pyqt 4.*
        - pyopengl 3.1.0
        - theano

test:
  commands:
    - e2version.py
    - e2speedtest.py
    - e2display.py -h
    - test -f ${PREFIX}/examples/mpi_test.py                        # [not win]
    - if not exist %LIBRARY_PREFIX%\\examples\\mpi_test.py  exit 1  # [win]
