package:
    name: eman2
    version: 2.2

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "python 2.7.*",
            "boost 1.61.*",
            "fftw",
            "numpy",
            "ftgl",
            "freetype",
            "gsl",
            "hdf5",
            "jpeg",
            "libtiff",
            "libpng",
            "szip",  # [win]
            "zlib",
    ] %}
    
    build:
        - cmake
        
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
        
        - bsddb  # [not win]
        - matplotlib
        - ipython
        - pyqt 4.*
        - pyopengl 3.1.0
        - theano
