package:
    name: eman2
    version: 2.21

source:
    path: {{ RECIPE_DIR }}/../..

build:
  script_env:
   - EMAN_TEST_SKIP  # [osx]

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py
    - tests/run_tests.sh
    - tests/run_tests.bat

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
