version: 2

jobs:
  build_no_recipe:
    machine: true
    environment:
      - MINICONDA_FILE: "Miniconda2-4.4.10-Linux-x86_64.sh"
    steps:
      - checkout
      - run: bash ci_support/build_no_recipe.sh

  build_recipe:
    machine: true
    environment:
      - MINICONDA_FILE: "Miniconda2-4.4.10-Linux-x86_64.sh"
    steps:
      - checkout
      - run: bash ci_support/build_recipe.sh

workflows:
  version: 2
  build_recipe_and_no_recipe:
    jobs:
      - build_no_recipe
      - build_recipe
